server:
  port: 8095

spring:
  profiles:
    active: prod
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    host: 121.196.111.69
    database: 6
    password: "062314"
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  security:
    user:
      name: admin
      password: 123456
      roles: SUPERUSER

mybatis-plus:
  type-enums-package: com.buko.db.designticketingsystem.enumerate
  type-aliases-package: com.buko.db.designticketingsystem.po
  configuration:
    map-underscore-to-camel-case: true



